package:
    name: cbf
    version: 1.0.4
source:
#    git_tag: 1.0.0
#    git_url: https://github.psi.ch/scm/cu/cbf.git
    path: ..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy

about:
    home: https://github.com/paulscherrerinstitute/cbf
    summary: "Python library for reading and writing CBF files."
