package:
    name: cbf
    version: 1.1.4
source:
    path: ..

requirements:
    build:
        - m2w64-make [win]
        - {{ compiler('python_c') }}
        - python
        - setuptools
        - numpy
    run:
        - python
        - numpy

about:
    home: https://github.com/paulscherrerinstitute/cbf
    summary: "Python library for reading and writing CBF files."
